paths:
  /algorand/poll:
    post:
      tags:
        - 'algorand'
      summary: 'Poll the status of a transaction'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/AlgorandPollRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/AlgorandPollResponse'